### ISSUE TITLE
Definition for rule 'react/jsx-no-duplicate-props' was not found

### ISSUE THREAD

**Issue by gsklee** [ricardofbarros/linter-js-standard#103]
After updated to 3.3.0 I'm getting this warning in nearly every React-related files I opened.

**Comment by gsklee** [comment]
I'm using `semi-standard` btw.

**Comment by nikmartin** [comment]
I just started getting this today after updating all my packages.

**Comment by gsklee** [comment]
@ricardofbarros Any ideas?

**Comment by ricardofbarros** [comment]
Hey @gsklee since `3.3.0` this package uses the `standard`, `semistandard` relative to the project node_modules if it doesn't find any it just uses the default version inside this package. 

Check if the `semistandard` you have on your project is up to date.

**Comment by sonicdoe** [comment]
Given the age of this issue, I’m going to close it. If anyone is still running into this, please let me know and I’ll take a closer look.
