### ISSUE TITLE
Definition for rule 'jsx-quotes' was not found.

### ISSUE THREAD

**Issue by patrickarlt** [ricardofbarros/linter-js-standard#104]
I get a `Definition for rule 'jsx-quotes' was not found.` whenever this tries to lint a file. I am using the latest versions of everything and have tried uninstalling/reinstalling the packages. I also seem to get this using both the standard and semistandard rule sets.
![screen shot 2016-04-13 at 1 08 47 pm](https://cloud.githubusercontent.com/assets/378557/14507720/e2c6cd5e-0178-11e6-919e-897a6a3b2991.png)

![screen shot 2016-04-13 at 1 07 09 pm](https://cloud.githubusercontent.com/assets/378557/14507678/a64b0db8-0178-11e6-9bd6-778ec704b136.png)

**Comment by sonicdoe** [comment]
Given the age of this issue, I’ll close it. @patrickarlt If you’re still running into this, let me know and I’ll reopen.
