### ISSUE TITLE
Support for xo

### ISSUE THREAD

**Issue by LinusU** [ricardofbarros/linter-js-standard#110]
How about adding support for [xo](https://github.com/sindresorhus/xo)? Thanks!

**Comment by tcarlsen** [comment]
use this: https://github.com/sindresorhus/atom-linter-xo

**Comment by ricardofbarros** [comment]
Thank you @tcarlsen

**Comment by LinusU** [comment]
@ricardofbarros @tcarlsen The thing I love about this package is that it automatically finds the appropriate linter to use from the package.json. I don't personally use xo, but ever so often I need to edit projects that does. Instead of getting errors on almost every single row, it would be nice if it would automatically detect xo and show those rules instead.

`semistandard` and `happiness` is implemented, so why not `xo`?

**Comment by LinusU** [comment]
ping @ricardofbarros, would you mind reading my last comment and please reconsider?

**Comment by ricardofbarros** [comment]
Hey @LinusU, I stand with @tcarlsen opinion, you should have both linters installed, and from a quick look at `atom-linter-xo` it only lints if `xo` is a dependency or devDependency in your project package.json. So you could use both linters without a problem. I could add `xo` support in the future, but I want to minimize the options of linter we have than rather increase them.

**Comment by LinusU** [comment]
Thank you for taking the time to answer. While I do not share your outlook on this, I do respect your decision.

For anyone else finding this, ticking "Check for standard" helped a lot 👍 That way it won't complain when another style guide is in use...
