### ISSUE TITLE
Cannot find module 'wrappy'

### ISSUE THREAD

**Issue by mnquintana** [ricardofbarros/linter-js-standard#111]
After some investigation, it seems that this package is throwing an error about not being able to find `wrappy` on any lint event passed on by the main `linter` package. Let me know if there's any more information you need!

![image](https://cloud.githubusercontent.com/assets/823545/14903139/03ca31c6-0d54-11e6-8898-d5ffebcca1f8.png)

linter-js-standard 3.3.2
linter 1.11.4

**Comment by ricardofbarros** [comment]
Probably a dirty install. Can't reproduce.
