### ISSUE TITLE
Causing Atom 1.7.3 to crash

### ISSUE THREAD

**Issue by joshmanders** [ricardofbarros/linter-js-standard#112]
I cannot figure out why, but once I deleted all my packages and installed them one by one all over again and the only one to cause it to crash is `linter-js-standard@3.3.2`

https://github.com/atom/atom/issues/11719

**Comment by joshmanders** [comment]
Anything? This  is still happening.

**Comment by joshmanders** [comment]
Seems the latest release has fixed this.

**Comment by ricardofbarros** [comment]
Great :)

**Comment by joshmanders** [comment]
Updated to 1.8.0 and it seems to be happening again :/

**Comment by dotmagic** [comment]
@joshmanders I'm using 1.9.8 and it works fine. Which OS are you using?

**Comment by joshmanders** [comment]
Seems that if you specify `standard` in your `package.json` before it's installed, it kills atom.
