### ISSUE TITLE
Definition for rule 'react/jsx-no-duplicate-props' was not found 

### ISSUE THREAD

**Issue by ricardofbarros** [ricardofbarros/linter-js-standard#114]
Hey @lubien, moving this [conversation](https://github.com/Flet/semistandard/issues/38#) to here.

This is odd, as this type of bugs were fixed as of `3.3.0` with #101 PR. 

Can you give me a small code sample so I can try replicate this?

**Comment by lubien** [comment]
Well, actually I'm using eslint for the project. If you don't mind, I can push to my github.

**Comment by ricardofbarros** [comment]
Sure, just drop a link to the raw file.

**Comment by lubien** [comment]
[Here](https://github.com/lubien/boilerplate-dummy). Try going to `./server/app.js`

**Comment by ricardofbarros** [comment]
Hey @lubien just cloned your repo and did a fresh install and `linter-js-standard` is working fine. No `react/jsx-no-duplicate-props` message, could you clean your node_modules dir and do a fresh install?

From what I'm seeing on your project your npm test script is running `semistandard`, which is getting the global semistandard, that could be why running on your CLI you don't get nothing and when you use `linter-js-standard` you get an error, possibly because you have an outdated `semistandard` under your project.

**Comment by lubien** [comment]
Cleaned `node_modules` and installed again. Nothing changed.
Also using `"lint": "./node_modules/.bin/semistandard"` still have the [empty result](http://i.imgur.com/L0fa3JN.png). 
About the `semistandard` version. I've installed today, so...

**Comment by ricardofbarros** [comment]
Hmm, can you tell me what are the settings you have of `linter-js-standard` ? Do you have `Check for standard` ticked?

**Comment by lubien** [comment]
It's like [this](http://i.imgur.com/DIJJkbC.png)

**Comment by ricardofbarros** [comment]
What's happening is that linter-js-standard is linting with the default linter, I can do version bump on `linter-js-standard` updating the default versions, but that' something I wish to stay away on the future of this package. It should always get `standard`, `semistandard` from node_modules

**Comment by jsejcksn** [comment]
@ricardofbarros I'm having this issue, too. How can I help? I just installed `linter-js-standard` from inside Atom settings and am using `semistandard` as the only deviation from the default package settings. I get the error in every JS file at the beginning of the first expression.

**Comment by ricardofbarros** [comment]
Hey @jsejcksn, yes `linter-js-standard` requires a package.json with `devDependencies` set with `standard` or `semistandard`, etc ..

Can you tell me your OS? Is it Win 10 as well ?

**Comment by jsejcksn** [comment]
@ricardofbarros I'm using OS X 10.11.5.

**Comment by ricardofbarros** [comment]
@jsejcksn do you have the same settings as [here](http://i.imgur.com/DIJJkbC.png), or at least `Check for standard` ticked?

**Comment by jsejcksn** [comment]
@ricardofbarros 
<img width="605" alt="linter-js-standard-settings" src="https://cloud.githubusercontent.com/assets/868251/15457142/a12a7720-2049-11e6-9638-6fa76daa52a9.png">

**Comment by ricardofbarros** [comment]
@jsejcksn I'm going to remove the option `Check for standard` in the future as it should be always enabled, but if you want to use the `semistandard` version you have installed under your project you should tick that option :) .

**Comment by jsejcksn** [comment]
@ricardofbarros Why is a `package.json` file required? I often use linters with individual files which are not associated with a package and have no `package.json` file.

**Comment by ricardofbarros** [comment]
Well, this is odd. Normally everyone has a `package.json` on the root of their project while they are editing their files.

 But oh well, I'm tired of this issues about `Definition react... not found` and I'm going to release a patch version with update versions of `standard`, `semistandard` and so on.

**Comment by ricardofbarros** [comment]
@jsejcksn  and @lubien, just released a patch version with updated dependencies. So now you can both update `linter-js-standard` and you'll have the most recent linters. Thanks.
