### ISSUE TITLE
Rules not up-to-date

### ISSUE THREAD

**Issue by gsklee** [ricardofbarros/linter-js-standard#12]
Some newer changes are not being merged in, eg. https://github.com/feross/eslint-config-standard/pull/1

**Comment by ricardofbarros** [comment]
This package doesn't have the need to merge the changes that happens on standard, I just need to increase the version of standard on the dependencies, I'll update the dependency and see if everything is okay.

**Comment by gsklee** [comment]
@ricardofbarros :+1:

**Comment by ricardofbarros** [comment]
Fixed on the last release, going to close. thank you :+1:

**Comment by gsklee** [comment]
@ricardofbarros Cool!
