### ISSUE TITLE
Indentation Issues

### ISSUE THREAD

**Issue by virginc** [ricardofbarros/linter-js-standard#122]
It's a JSX file.
<img width="726" alt="index_jsx_ __users_virginia_workspace_vubeology_v" src="https://cloud.githubusercontent.com/assets/2243885/16697625/2c628e8c-4510-11e6-9d99-df5556332971.png">

Apparently this is an issue with the latest version of happiness. Any way that we can revert to 5.5.0?

**Comment by virginc** [comment]
The settings are set to happiness

**Comment by ricardofbarros** [comment]
Hey @virginc, you could use your custom version of happiness. You just need to tick `checkStyleDevDependencies` option and it will try to find the linter on your `node_modules`. thx
