### ISSUE TITLE
Check style on devDependencies and honour standard spec to ignore files

### ISSUE THREAD

**Issue by ricardofbarros** [ricardofbarros/linter-js-standard#13]
As @xicombd suggested through one of our conversations, we should have a checkbox on settings with the following label or something alike:

`- Check code style on devDependencies`

If this option was checked the plugin should parse the project `package.json` and read `devDependencies`. If `standard` or `semistandard` were present on development dependencies the linter should lint accordingly. If none of those were present it should not fallback to `standard` style it simply should not lint.

And we should start honouring `standard` ignore specification as described in standard documentation.

```js
"standard": {
  "ignore": [
    "**/out/",
    "/lib/select2/",
    "/lib/ckeditor/",
    "tmp.js"
  ]
}
```

**Comment by xicombd** [comment]
This would be awesome :+1:

**Comment by ricardofbarros** [comment]
This features were implemented in the last release.

**Comment by xicombd** [comment]
\o/

Thank you!!
