### ISSUE TITLE
Double quotes in React code

### ISSUE THREAD

**Issue by rllola** [ricardofbarros/linter-js-standard#135]
Hi,

How to deactivate the double quote warning in React code ?

**Comment by ricardofbarros** [comment]
Hey @rllola, could you give a code example? thx

**Comment by ricardofbarros** [comment]
This seems a duplicated of #156.

**Comment by rllola** [comment]
Hi,

The new version of standard authorize the double quote in react now but the linter still give me an error. Any idea why ?
