### ISSUE TITLE
Install failed.

### ISSUE THREAD

**Issue by lygstate** [ricardofbarros/linter-js-standard#136]
C:\CI-Tools\IDE\Atom-Arop\.atom>call apm install --production linter-js-standard
Installing linter-js-standard to C:\CI-Tools\IDE\Atom-Arop\.atom\packages failed

> spawn-sync@1.0.15 postinstall C:\Users\lygstate\AppData\Local\Temp\apm-install-dir-116715-6108-1f4nngw\node_modules\linter-js-standard\node_modules\happiness\node_modules\happiness-format\node_modules\esformatter\node_modules\npm-run\node_modules\spawn-sync
> node postinstall

Installing native dependencies (this may take up to a minute)

> spawn-sync@1.0.15 postinstall C:\Users\lygstate\AppData\Local\Temp\apm-install-dir-116715-6108-1f4nngw\node_modules\linter-js-standard\node_modules\standard\node_modules\standard-format\node_modules\esformatter\node_modules\npm-run\node_modules\spawn-sync
> node postinstall

Installing native dependencies (this may take up to a minute)

> spawn-sync@1.0.15 postinstall C:\Users\lygstate\AppData\Local\Temp\apm-install-dir-116715-6108-1f4nngw\node_modules\linter-js-standard\node_modules\semistandard\node_modules\semistandard-format\node_modules\standard-format\node_modules\esformatter\node_modules\npm-run\node_modules\spawn-sync
> node postinstall

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine get-stdin@5.0.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine get-stdin@5.0.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\CI-Tools\\IDE\\Atom-Arop\\Atom\\resources\\app\\apm\\bin\\node.exe" "C:\\CI-Tools\\IDE\\Atom-Arop\\Atom\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\CI-Tools\\IDE\\Atom-Arop\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\CI-Tools\\IDE\\Atom-Arop\\.atom\\.apmrc" "install" "C:\\Users\\lygstate\\AppData\\Local\\Temp\\d-116715-6108-1lk58ul\\package.tgz" "--target=0.37.8" "--arch=ia32" "--production"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file C:\windows\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

**Comment by Ankitdave87** [comment]
Same issue 

**apm -v**
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 1.9.5.msysgit.1
visual studio 2012

**apm install linter-js-standard**
`Installing linter-js-standard to C:\Users\EMPOWER\.atom\packages failed

> spawn-sync@1.0.15 postinstall C:\Users\EMPOWER\AppData\Local\Temp\apm-install-dir-116720-1012-tb0199\node_modules\linter-js-standard\node_modules\standard\node_modules\standard-format\node_modules\esformatter\node_modules\npm-run\node_modules\spawn-sync
> node postinstall

Installing native dependencies (this may take up to a minute)

> spawn-sync@1.0.15 postinstall C:\Users\EMPOWER\AppData\Local\Temp\apm-install-dir-116720-1012-tb0199\node_modules\linter-js-standard\node_modules\happiness\node_modules\happiness-format\node_modules\esformatter\node_modules\npm-run\node_modules\spawn-sync
> node postinstall

Installing native dependencies (this may take up to a minute)

> spawn-sync@1.0.15 postinstall C:\Users\EMPOWER\AppData\Local\Temp\apm-install-dir-116720-1012-tb0199\node_modules\linter-js-standard\node_modules\semistandard\node_modules\semistandard-format\node_modules\standard-format\node_modules\esformatter\node_modules\npm-run\node_modules\spawn-sync
> node postinstall


npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine get-stdin@5.0.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine get-stdin@5.0.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\EMPOWER\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\EMPOWER\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\EMPOWER\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\EMPOWER\\.atom\\.apmrc" "install" "C:\\Users\\EMPOWER\\AppData\\Local\\Temp\\d-116720-1012-1vdq15q\\package.tgz" "--target=0.37.8" "--arch=ia32" "--msvs_version=2012"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

`

**Comment by lygstate** [comment]
upgrade to atom beta resolve the issue
