### ISSUE TITLE
The known issue might be solved

### ISSUE THREAD

**Issue by bvhme** [ricardofbarros/linter-js-standard#14]
The bug that the known issue points to in the readme is marked as solved, is this issue still relevant?

**Comment by ricardofbarros** [comment]
Hello, probably isn't relevant anymore, since we are using `standard` and `semistandard` bins from the project `node_modules` directory and not from the global path. I will remove it when I release the next major version (#13). 

Thank you.

**Comment by ricardofbarros** [comment]
Removed it.
