### ISSUE TITLE
Proposal of additional standard

### ISSUE THREAD

**Issue by hanakin** [ricardofbarros/linter-js-standard#142]
Hey guys love the package my only issue with these standards (which are great by the way), and the one rule i feel should be configurable is the spacing of indent this should always be an option. 

This is a global programming concern as we often mix various languages often, some of which require 2 spaces and some of which require 4 spaces, others hat require hard tabs.

since there is a format for 2 spaces and hard tabs I made a version with 4 space soft tabs to meet this need.

https://github.com/hanakin/sane-format

please consider adding it to the package thks

**Comment by ricardofbarros** [comment]
Hey @hanakin I think we should stop with the madness of creating custom standard that only change a small set of rules. I would suggest you to use [xo](https://github.com/sindresorhus/xo#space) as you can configure the spaces.
