### ISSUE TITLE
Publish to APM

### ISSUE THREAD

**Issue by declandewet** [ricardofbarros/linter-js-standard#147]
Any ETA on when we can expect #141 to land?

**Comment by Kaijun** [comment]
+1
I'm using vue and need this urgently!

**Comment by declandewet** [comment]
@Kaijun you can use it right now by doing the following:

1. Open your terminal
2. Uninstall `linter-js-standard`: `$ apm uninstall linter-js-standard`
3. Reinstall `linter-js-standard` from the `master` branch: `$ apm install https://github.com/ricardofbarros/linter-js-standard`

**Comment by Kaijun** [comment]
@declandewet thanks!

**Comment by Kaijun** [comment]
@declandewet it still doesn't work on my side, should i configure anything?

**Comment by Kaijun** [comment]
@declandewet OK i found it. `Lint HTML Files` should be toggled under pref panel

**Comment by declandewet** [comment]
✌️

**Comment by ricardofbarros** [comment]
Sorry guys, I forgot to publish it to apm, I will do this at the end of the day. Sorry... @declandewet @Kaijun

**Comment by Kaijun** [comment]
@ricardofbarros I'm not pretty sure if you published the right version to APM. 

At least, on my side, using `apm install https://github.com/ricardofbarros/linter-js-standard` works. 

but using the latest version on APM still has problem. Although the `Lint HTML Files` option already appears and i also toggled it on.

**Comment by marvinroger** [comment]
It's not published yet, I guess.

**Comment by ricardofbarros** [comment]
Done, published as `@3.5.0`
