### ISSUE TITLE
dependency "standard" too old

### ISSUE THREAD

**Issue by itsnotvalid** [ricardofbarros/linter-js-standard#149]
Just looked into the upstream package [standard](https://github.com/feross/standard), the current version is something like 8.X.0. However, linter here only use the version 5 series, which is a year old (last update was in Nov 8, 2015). Some people complaining that ES8 features are not supported, for example, and those would have been fixed in newer version of `standard`.

Thanks.

**Comment by ricardofbarros** [comment]
Hey @itsnotvalid , you're right, I updated the other linter but somehow I forgot to update standard.

**Comment by jonaswindey** [comment]
Could you please update `standard`and publish a new version? It's the core of this linter so it should be up to date.

**Comment by taoeffect** [comment]
request++

**Comment by jonaswindey** [comment]
https://github.com/ricardofbarros/linter-js-standard/pull/151

**Comment by taoeffect** [comment]
@jonaswindey Yeah, forking this repo, bumping the version, and then using the `apm` tool to install it worked for me. 👍

**Comment by ricardofbarros** [comment]
Hey, sorry for the late response but #151 is merged. Thanks

**Comment by ricardofbarros** [comment]
It's published on [`v3.7.0`](https://github.com/ricardofbarros/linter-js-standard/releases/tag/v3.7.0)
