### ISSUE TITLE
Unexpected usage of doublequote. (jsx-quotes)

### ISSUE THREAD

**Issue by keul** [ricardofbarros/linter-js-standard#156]
On a jxs formatted source I get the warning in the subject on a code like this ones:

    <div className="clearfix content-wrapper">

As single/double quotes on JSX is very opinionated, there's a way to change this default to doublequote or at least read the .eslintrc settings?

**Comment by LinusU** [comment]
The whole idea with standard is that nothing is configurable, so there is currently no way to change this.

**Comment by ricardofbarros** [comment]
Pretty much what @LinusU  said. You could disable the rules of eslint for that specific line or block, though.

**Comment by kingram6865** [comment]
> Pretty much what @LinusU said. You could disable the rules of eslint for that specific line or block, though.

How would that be done?
