### ISSUE TITLE
How to ignore some warnings ?

### ISSUE THREAD

**Issue by tongjieme** [ricardofbarros/linter-js-standard#160]
Hello,

I am new to Atom, just came across linter-js-standard package. 
And I want to ignore some warnings such as "Extra semicolon" "Strings must use singlequote".
But I couldn't find an answer in README.md and Google search results. 

Thank You.

**Comment by ricardofbarros** [comment]
Standard and it's variants are basically eslint, you could use:

```
const is_name = 'Ricardo' // eslint-disable-line camelcase
```

That just an example, I recommend you read the documentation. 

http://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments
