### ISSUE TITLE
[weird] parsing error: illegal 'use strict' directive.....

### ISSUE THREAD

**Issue by jessevdp** [ricardofbarros/linter-js-standard#161]
The following error is shown to me by js-standard: 

```
parsing error: illegal 'use strict' directive in function with non simple parameter list
```

I googled and the error should be thrown when `'use strict'` is used within a function with a non simple parameter list. (such as the function shown in the screenshot)

However, There is no `'use strict'` specified in the entire document... As shown by the search. 

<img width="929" alt="screen shot 2017-02-07 at 19 13 22" src="https://puu.sh/tSCrh/63cbbebf44.png">

**Comment by ricardofbarros** [comment]
Can you create a minimal gist file that replicates the same issue?

**Comment by jessevdp** [comment]
Oh yeah, will do. I think it's basically in any function where you specify the defaults for parameters es6 style like so

⋅⋅⋅js
function foo (bar = 'bar') {}
⋅⋅⋅

**Comment by ricardofbarros** [comment]
Hey @jessevdp , I've just tested and I can't find any error with that statement. What is your `standard` version ?

**Comment by jessevdp** [comment]
The error seems to be gone now, I updated the `standard-linter` package this morning. I'm on `v3.9.0` now.

**Comment by sonicdoe** [comment]
Since it looks like this has been resolved, I’ll close this issue.
