### ISSUE TITLE
where is Linter?

### ISSUE THREAD

**Issue by zzzgit** [ricardofbarros/linter-js-standard#162]
This extension depends on `Linter`,right?
But I can't find `Linter` in atom's package installation panel

**Comment by ricardofbarros** [comment]
Hey @zzzgit, you can follow the instructions of the repo https://github.com/steelbrain/linter

but that's odd you should find linter on installation panel. `atom-community/linter`

**Comment by Arcanemagus** [comment]
Unfortunately the search functionality for packages in Atom is... rather bad and `Linter` is _quite_ far down in the list of results. It's one of the reasons most providers automatically install it for you.
