### ISSUE TITLE
"Extra semicolon" - no sense, need to disable

### ISSUE THREAD

**Issue by sebfindling** [ricardofbarros/linter-js-standard#164]
Hi guys. I love this package and use it a lot, but I want to disable the warning for end-line semicolons since I personally find it standard and a good practices in JS, especially for minification and easines of reading purposes. 

How can I disable this or could you please add a setting for it?

**Comment by ricardofbarros** [comment]
Hey @sebfindling , that's the purpose of standard, you shouldn't need to disable it. If you want to use semi-colons try [`semistandard`](https://github.com/Flet/semistandard) instead. This package supports it.

**Comment by sebfindling** [comment]
Ohh, didn't notice semistandard used semicolons. Thanks ;)

**Comment by ricardofbarros** [comment]
No problem :) It's the only difference between styles.
