### ISSUE TITLE
How do I select which style should be used for each project ?

### ISSUE THREAD

**Issue by gfviegas** [ricardofbarros/linter-js-standard#167]
Hi, I might be missing something here, but the docs are not clear enough if so.

I have projects where I use semi-standard, and others that uses standard. Is there a way to tell the linter to use "standard" on the project B and to use "semi" on project A? 

I know there's the `checkStyleDevDependencies` option, but it'll disable the lint for all projects which I don't have (or I just can't, like 3rd party plugins), and I don't want that, I just want to tell linter to use the style A or B, not to disable it to others.

Wouldn't be nice if we look in package.json for an option like `style: 'semi-standard'`, or something?

**Comment by gfviegas** [comment]
@ricardofbarros ?

**Comment by ricardofbarros** [comment]
Hey @gfviegas, is there something stopping you to install & save `standard` / `semistandard` to those project's devDependencies ?

**Comment by sonicdoe** [comment]
If you want to override the style for a specific project, you’ll have to install `standard` (or `semistandard`) locally. *However*, you do not have to enable the `checkStyleDevDependencies` as linter-js-standard will always prefer the local version.

I’ll look into improving the documentation in the future.
