### ISSUE TITLE
Is there an alternative to disable/enable when switching to/from standard projects?

### ISSUE THREAD

**Issue by justin-calleja** [ricardofbarros/linter-js-standard#172]
I'm using Standard for my new projects. The only problem is, when I work on old project's or other people's projects, I end up having to disable this plugin as it litters the codebase with warnings (these projects do have their own `.eslintrc` / `.eslintrc.json` files).

Is there a way to avoid this? Or will there be future support for auto-detecting this (e.g. `standard` in `devDependencies`) and auto-enable/disable?

**Comment by ricardofbarros** [comment]
Hey @justin-calleja, if you don't have  `standard` as dependency on those projects you could easily disable it, by ticking `checkStyleDevDependencies ` option to true.

**Comment by justin-calleja** [comment]
Thanks @ricardofbarros 

I ticked "Check for standard" under "Settings" (for other's ref)
