### ISSUE TITLE
Ignore certain paths by default

### ISSUE THREAD

**Issue by ricardofbarros** [ricardofbarros/linter-js-standard#18]
New option to be implemented: 

Ignore node_modules/**, default: `true`

**Comment by ricardofbarros** [comment]
```
   'coverage/**',
   'node_modules/**',
   '**/*.min.js',
```

**Comment by sonicdoe** [comment]
[standard already ignores certain paths by default](https://github.com/standard/standard#how-do-i-ignore-files). It would make sense to ignore the same paths in linter-js-standard.

**Comment by sonicdoe** [comment]
standard’s default ignores seem to be working nowadays. This is probably due to passing the `filename` to `lintText()` since [v5.0.0](https://github.com/ricardofbarros/linter-js-standard/blob/master/CHANGELOG.md#500-2018-03-04).
