### ISSUE TITLE
I got an reserved word error for await statements

### ISSUE THREAD

**Issue by rbecheras** [ricardofbarros/linter-js-standard#185]
![capture d ecran de 2017-05-11 22-18-44](https://cloud.githubusercontent.com/assets/6469390/25970127/d6f9067c-3697-11e7-998a-cb6a005a1dc2.png)

But I use `linter-js-standard v3.9.1`:

![capture d ecran de 2017-05-11 22-19-36](https://cloud.githubusercontent.com/assets/6469390/25970197/0175956e-3698-11e7-9857-382acf736f78.png)
 
Which use `standard v8.6.0` as dependency

> https://github.com/ricardofbarros/linter-js-standard/blob/master/package.json

And `standard` seems support `async/await` since `standard v8.3.0` (`> v8.6.0`)

> https://github.com/feross/standard/issues/645#issuecomment-250550504

![capture d ecran de 2017-05-11 22-22-38](https://cloud.githubusercontent.com/assets/6469390/25970298/63e6dbe0-3698-11e7-9dfe-66358c96cf19.png)

What's wrong ?

**Comment by sonicdoe** [comment]
This was already answered in https://github.com/standard/standard/issues/884#issuecomment-307155068:

> I think this is working normally. The error isn't very informative, but the `await` keyword can only be used inside of a function marked `async`. So the sample above is correctly marked as an error.
