### ISSUE TITLE
When switching projects, still can see lint errors from previous projects

### ISSUE THREAD

**Issue by binarykitchen** [ricardofbarros/linter-js-standard#186]
Happens on v3.9.1 - easy to reproduce:

1. Open a project and have js-standard lint errors in them and they are visible at bottom in their own panel.
2. Do not fix them, just switch to another project
3. That panel at bottom is still there, listing those linting errors from previous project.

I expect them to disappear when switching to another project and have the linter run again for that new project or so.

**Comment by sonicdoe** [comment]
I’m not able to reproduce this under v3.9.1. How do you switch to another project? Do you open it in a new window?

Either way, v3.9.2 might have fixed this. Could you let me know if that is the case for you?

**Comment by sonicdoe** [comment]
Closing due to lack of response.
