### ISSUE TITLE
Disable when an ESLint configuration file was found

### ISSUE THREAD

**Issue by chee** [ricardofbarros/linter-js-standard#194]
it would be quite nice if this would not try and lint in projects that have a `.eslintrc*` in them.
or perhaps projects that have a package.json but do not (dev)depend on `standard`

**Comment by sonicdoe** [comment]
I think this makes sense and I’d suggest we disable linting if there is an [ESLint configuration file](http://eslint.org/docs/user-guide/configuring#configuration-file-formats) or the `package.json` has an `eslintConfig` property. PR welcome!
