### ISSUE TITLE
Remove warning for localStorage?

### ISSUE THREAD

**Issue by pawel2105** [ricardofbarros/linter-js-standard#201]
How can I remove warnings for definition of localStorage? In a JS file I can use it without issue but the plugin complains about a lack of definition.

```
localStorage.setItem('email', response.data.email)
```

I don't want to use comment exceptions since localStorage (in my case) is used quite a lot throughout a project and I don't want to litter files with linting exception comments. Is there a global entry I can add or something?

**Comment by sonicdoe** [comment]
There are multiple ways to solve this but [standard itself suggests to always prefix with `window`](https://standardjs.com/index.html#the-rules):

> Always prefix browser globals with `window` – except `document` and `navigator` are okay.
> Prevents accidental use of poorly-named browser globals like `open`, `length`, `event`, and `name`.

See also https://github.com/standard/standard/issues/976.

**Comment by pawel2105** [comment]
@sonicdoe of course! Thank you.
