### ISSUE TITLE
Destructing params in functions / constructors

### ISSUE THREAD

**Issue by Eldar-X** [ricardofbarros/linter-js-standard#202]
I got error message "args is not defined" when try to make this
`module.exports = class People {
  constructor ({name, age = 0} = args) {
    this.name = name
    this.age = age
  }
}
`

Even when i set parser (babel-eslint / esprima) in package.json i don't see any changes

**Comment by Arcanemagus** [comment]
Destructuring can only be used where data is "received", primarily the left hand side of an assignment. You can use destructuring by simply doing `constructor ({name, age = 0})` which, when fed an Object that has properties of `.name` and `.age` (defaulting to 0) it will create variables of those names. I'm assuming that's what you were aiming for here?

What you have written right now is likely being interpreted as a destructuring assignment like above, but with a _default value_ of `args` (which isn't defined).

This has nothing to do with `standard`, or `linter-js-standard` though 😛, other than them telling you about this bug.

**Comment by Eldar-X** [comment]
you are right it's my bad 😃
