### ISSUE TITLE
Project Wide Errors + Nuclide

### ISSUE THREAD

**Issue by followbl** [ricardofbarros/linter-js-standard#207]
Am I drunk or did this plugin use to show all the linting errors for the entire project by default, with the option to drill into "Current file only"...

Ps. I'm using Nuclide, with "Linter" disabled...it works great, just without the global linting errors, which I like and find useful 😺 

Thanks for the package 😎 🐠 🌴

**Comment by Arcanemagus** [comment]
It's been `file` scoped from [the beginning](https://github.com/ricardofbarros/linter-js-standard/commit/e340405893ab4c8a769fa030bc66d650d7da465f#diff-3c55856d3a1a715a31d1a543d45432afR10) so... drunk or something Nuclide is/was doing? 😛

**Comment by followbl** [comment]
@Arcanemagus thanks for the answer, I'll look into nuclides change-log
