### ISSUE TITLE
Does not recognize env in package.json

### ISSUE THREAD

**Issue by 50Wliu** [ricardofbarros/linter-js-standard#209]
Given:
![standard-package-json-setup](https://user-images.githubusercontent.com/2766036/32463901-6d45e2c0-c33e-11e7-8a64-dec9930e01b6.png)
and:
![linter-js-standard-settings](https://user-images.githubusercontent.com/2766036/32463931-84d16e0a-c33e-11e7-87e1-b4924815a406.png)
this is what I see:
![diagnostics-view-errors](https://user-images.githubusercontent.com/2766036/32463961-ac4af76c-c33e-11e7-8280-bcaf8e9afdf9.png)

Running `standard` from the command line gives 0 errors.

Please tell me if you need more information.

**Comment by sonicdoe** [comment]
Thanks for reporting, I was able to reproduce this issue. I’ll try to roll out a fix soon.

**Comment by sonicdoe** [comment]
v4.0.3 should fix this issue. @50Wliu Let me know if you’re still running into problems.

**Comment by 50Wliu** [comment]
Thank you!
