### ISSUE TITLE
Wrong indentation warning for nested JS templates

### ISSUE THREAD

**Issue by mercmobily** [ricardofbarros/linter-js-standard#223]
Hi,

I am not sure if this belongs to linter itself or here.
This is a small example to show the problem:
(I realise the code doesn't do much, it was working code butchered for brevity)

    function render () {
      const {html, _items} = this;
      return html`
        <style>
          :host { display: block; }
        </style>
        <p ?hidden="${_items.length !== 0}">Please add some products to cart.</p>
        ${_items.map((item) => {
          console.log('aaa')
        })}
      `;
    }
    render();

The `console.log` line gives a warning: `expected indentation of 4 spaces but found 6
The following line has the same problem.

Help?

**Comment by sonicdoe** [comment]
It looks like this issue actually occurs in `standard` (since v11), see https://github.com/standard/standard/issues/1056 and https://github.com/standard/standard/issues/1176. I see you also already opened an issue over at https://github.com/eslint/eslint/issues/10932.

**Comment by mercmobily** [comment]
I know but it looks like the issues stems from eslint more than standard... right?

**Comment by sonicdoe** [comment]
Yes, I think so too.

**Comment by mercmobily** [comment]
This issue depends on https://github.com/eslint/eslint/issues/10932 -- I am not sure how you deal with these cases in this repo. However, it's basically up to Eslint to fix it.

**Comment by sonicdoe** [comment]
Since there isn’t anything we can do about this in this plugin, I’ll go ahead and close this issue.
