### ISSUE TITLE
Also check typescript with .ts extensions

### ISSUE THREAD

**Issue by lukasoppermann** [ricardofbarros/linter-js-standard#225]
Hey @ricardofbarros,

this plugin is really useful. Sadly it is of little use to me by now, since I moved to typescript.
Please can you make it also check `.ts` or maybe add a settings input where one can specify which file extensions to check.

Thanks.

**Comment by lukasoppermann** [comment]
Nice, thanks. 👍

**Comment by sonicdoe** [comment]
This is now also published in v6.1.0 🎉 Be sure to set up JavaScript Standard Style [as described in their FAQ](https://standardjs.com/index.html#typescript). Let me know if it doesn’t work as intended.

**Comment by lukasoppermann** [comment]
Seems to work perfect. Thank you for the quick reaction.

**Comment by johnjcamilleri** [comment]
This is nice, but needs to be better documented. If I just install the `linter-js-standard` Atom package and then open a Typescript file, I get parse errors:

<img width="490" alt="Screenshot 2019-05-28 at 08 38 37" src="https://user-images.githubusercontent.com/376723/58456381-52d4e300-8124-11e9-8341-d4e9408a54db.png">

It took me ages to figure out that this error was actually coming from this package. It would be great to be able to disable Typescript support from the package's settings page.

**Comment by sjuvonen** [comment]
I used to like this package but unfortunately after having to work with TypeScript projects as well, this poorly implemented feature makes using linter-js-standard package totally impossible...
