### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by jimmywarting** [ricardofbarros/linter-js-standard#227]
You have [4 outdated dependencies](https://david-dm.org/ricardofbarros/linter-js-standard)
Would you care to update? maybe also adding the [greenkeeper](https://greenkeeper.io) bot?

**Comment by sonicdoe** [comment]
I have updated [semistandard](
https://github.com/ricardofbarros/linter-js-standard/commit/1504079e88449a7aabd2851fa91dce1c662715f1) and [babel-eslint](
https://github.com/ricardofbarros/linter-js-standard/commit/b7744b3f005ec8f361fafeb75e99603f779de682) on the `master` branch, for now. I’ll get to atom-package-deps and ignore when I can make time.

Thanks for the hint at Greenkeeper, however, I’m currently not interested in adding it to this repository.

**Comment by Arcanemagus** [comment]
FYI, it looks like you are already [defining the package name](https://github.com/ricardofbarros/linter-js-standard/blob/b7744b3f005ec8f361fafeb75e99603f779de682/lib/init.js#L61) when calling `install()`, and are on a [4.x version](https://github.com/ricardofbarros/linter-js-standard/blob/b7744b3f005ec8f361fafeb75e99603f779de682/package.json#L23) of `atom-package-deps`, so the 5.0.0 update should require no changes other than updating the version in `package.json`.

**Comment by sonicdoe** [comment]
Thanks for weighing in, @Arcanemagus.

I would have liked to take a closer look at when and how `atom-package-deps` v5 installs the latest version of a dependency. For example, if I specify `linter:2.0.0` as a dependency, would `atom-package-deps` install `linter` v2.0.0 or the latest version (as long as it‘s newer than v2.0.0)?

**Comment by Arcanemagus** [comment]
If you specify `linter:2.0.0` it will require _at least_ that version to be installed, and will install that version if it isn't.

So if the user has `linter@1.x.y` installed, it will force (with a prompt?) install `linter@2.0.0` _exactly_, meaning they will then have Atom telling them there is an update available.

If they have `linter@2.0.0` or newer installed, it will simply return without doing anything.

**Comment by sonicdoe** [comment]
Thanks for the explanation. I’ve just tested this with a fresh installation of Atom (to test the out-of-box experience) and it seems like `atom-package-deps` v5 installs *the latest version* of `linter` if none is installed. I actually like this change, however, I was also running into a regression bug which I’ve reported in https://github.com/steelbrain/package-deps/issues/140.

**Comment by Arcanemagus** [comment]
Oh interesting, I'm not sure if that's a bug in `apm` or not since I thought it sent that out as a command like `apm install linter@2.0.0`, but in either case I'm definitely with you that installing the latest version is preferred!
