### ISSUE TITLE
[bug] parsing error in react-native

### ISSUE THREAD

**Issue by xiaweiss** [ricardofbarros/linter-js-standard#228]
![image](https://user-images.githubusercontent.com/17960084/52945037-c8a21380-33ab-11e9-848f-aee1d91757b2.png)

[bug] when i create a new react-native app( 0.58.4 )，and installed "standard ^12.0.1" ，then delete annotation, the bug will appear

if I install standard 10.0.3，it worked no error

**Comment by sonicdoe** [comment]
Sorry, I’m not able to reproduce this. As far as I can tell, I have the same file as you and when I run `standard` against it, everything works fine. Do you experience this error only in Atom or also when running `standard` on the command line?

**Comment by xiaweiss** [comment]
only in Atom

**Comment by sonicdoe** [comment]
Do you have any custom `standard` settings in your `package.json`? If possible, could you share the full repository in which you encounter this error? I’ve used `react-native init` before but perhaps there are still some differences between your and my project.

**Comment by xiaweiss** [comment]
thank you
