### ISSUE TITLE
How do you set a global configuration?

### ISSUE THREAD

**Issue by mercmobily** [ricardofbarros/linter-js-standard#229]
Hi,

Thanks for the fantastic work.
I would like to set a bunch of default settings. For example, I am getting "js-standard: customElements is not defined". I would like to set customElements as a global variable for the WHOLE project. Or, I would like to set the project as a browser one so that these warnings go away.

Is it possible to do so? How?

**Comment by Arcanemagus** [comment]
This is answered in the `standard` FAQ:

[I use a library that pollutes the global namespace. How do I prevent "variable is not defined" errors?](https://standardjs.com/#i-use-a-library-that-pollutes-the-global-namespace-how-do-i-prevent-variable-is-not-defined-errors)

This package is simply a wrapper around `standard`, you should always look there first for how to change the output you are seeing.

**Comment by mercmobily** [comment]
Awesome, thank you so much for answering. I now have a much better understanding of what's happening under the hood.
