### ISSUE TITLE
Upgrade to standard 14.x so that we get the latest eslint with dynamic imports

### ISSUE THREAD

**Issue by mercmobily** [ricardofbarros/linter-js-standard#232]
ESLint finally has [dynamic imports](https://github.com/eslint/eslint/issues/11803). At the moment, linter-js-standard uses Standard version ^12.0.1. It would be great to upgrade to version 14.x so that we can benefit from the latest improvements in ESlint, and especially dynamic imports.

**Comment by sonicdoe** [comment]
standard has been upgraded to v14 in https://github.com/ricardofbarros/linter-js-standard/commit/0604e52883e76602747ccab8da891f960d02c4aa which has been released with linter-js-standard v7.0.0.

**Comment by mercmobily** [comment]
Thanks!
