### ISSUE TITLE
Kaspersky antivirus alert

### ISSUE THREAD

**Issue by ivan-nekic** [ricardofbarros/linter-js-standard#244]
Hi, on windows machine identifies the package as hoax and deletes it!
```
Component: File Anti-Virus
Result description: Deleted
Type: Software that may cause harm
Name: Hoax.JS.ExtMsg.a
Precision: Exactly
Threat level: Medium
Object type: File
Object name: _postinstall.js
Object path: C:\Users\iNekic\AppData\Local\Temp\apm-install-dir-202276-7332-3n4bbf.a9ggu\node_modules\linter-js-standard\node_modules\es5-ext
MD5: 7DE8D84BD9ECC1D0904048956C94817B
```

**Comment by sonicdoe** [comment]
Thank you for opening an issue! This was due to https://github.com/medikoo/es5-ext/issues/186. Since es5-ext is no longer a dependency in [linter-js-standard v8.0.0](https://github.com/ricardofbarros/linter-js-standard/releases/tag/v8.0.0), it should be fixed now.
