### ISSUE TITLE
Standard:global package.json support

### ISSUE THREAD

**Issue by killswitch** [ricardofbarros/linter-js-standard#25]
This supports `ignore` which is great, if I want to ignore a whole file, but I don't want to ignore files, I want it to not error out on me when I am writing tests. So support for global would be great. :)

```json
{
  "standard": {
    "global": [ "myVar1", "myVar2" ]
  }
}
```

Ref: https://github.com/feross/standard#i-use-a-library-that-pollutes-the-global-namespace-how-do-i-prevent-variable-is-not-defined-errors

**Comment by ricardofbarros** [comment]
I will look on this, thank you @killswitch

**Comment by killswitch** [comment]
Other than this request, I just started using this plugin and I love it. Thanks for the hard work @ricardofbarros!

**Comment by uiureo** [comment]
+1

**Comment by LeiZeng** [comment]
+1

**Comment by DadaMonad** [comment]
+1

**Comment by b3njamin** [comment]
:+1:

**Comment by ricardofbarros** [comment]
I see this is a very wanted feature, I'm on it.

**Comment by ricardofbarros** [comment]
It seems this isn't yet supported in standard CLI, 

btw thanks @LeiZeng by opening the [issue](https://github.com/feross/standard/issues/200) on standard.

**Comment by killswitch** [comment]
Thank you @ricardofbarros !

**Comment by feross** [comment]
The standard CLI supports `--global` now, as of 5.0.0-3. This is a prerelease version, so beware if you choose to depend on it, that breaking changes may be added before 5.0.0 is released.

**Comment by ricardofbarros** [comment]
@feross is 5.0.0 release around the corner? If so I prefer to wait, if not I will implement it now and wait for the release to fix possible breaking changes.

**Comment by ricardofbarros** [comment]
And thank you @feross for your awesome work :+1:

**Comment by feross** [comment]
We're waiting for eslint 1.0.0 before releasing standard 5.0.0. eslint released 1.0.0-rc1 last week, so it hopefully won't be too much longer.

I don't expect any breaking changes in the CLI. I meant that we might add/remove rules from the [list of new rules in 5.0.0](https://github.com/feross/standard/issues/192). :+1:

**Comment by killswitch** [comment]
Awesome, can't wait to see this.

**Comment by ricardofbarros** [comment]
As of @2.1.0 this feature is supported. :+1:

Thanks everyone.

**Comment by killswitch** [comment]
Awesome work @ricardofbarros
