### ISSUE TITLE
Package.json entry to ignore this codebase.

### ISSUE THREAD

**Issue by killswitch** [ricardofbarros/linter-js-standard#26]
So while I love this plugin, one thing I just realized now that I am using it, while I want to force all my code to follow feross' standard guide, sometimes I work in code where I can't.. Maybe put in support for having a entry in `package.json` that if found would allow you to just not run the linter on it at all.

For example:

```json
{
    "linter": false
}
```

Would then be picked up and it won't run at all.

**Comment by ricardofbarros** [comment]
I think I'm not following you on this, you can however turn on option `checkDevDependencies` on and it will search the `package.json` for a style if it doesn't find it simply doesn't lint. Is that what you want?

**Comment by killswitch** [comment]
Nah, like I open a project that doesn't follow any standards of this project or anything, I can put the flag in package.json and it'll ignore the whole project after that. So I don't get flooded with errors in my editor because the code I am in, can't be linted.

**Comment by ricardofbarros** [comment]
Like I'm saying you can do that just by having that option checked and not having nothing on `devDependencies` on your package.json

**Comment by ricardofbarros** [comment]
If that project doesn't follow any standard you shouldn't have anything on `devDependencies`

**Comment by killswitch** [comment]
But it still lints the project I am working in... That's what I am saying. I'm working on a client project that isn't in line with any of the standards, so now I have 207 issues showing and every line I click is barking at me.

**Comment by ricardofbarros** [comment]
Hmm strange could you confirm if you have the `Check Style Dev Dependencies` ticked and inside your package.json you don't have any `devDependencies`?

**Comment by killswitch** [comment]
Okay I see what you mean now. That option isn't very clear on what exactly it does. I had to tick the box, and then close the project and reopen it for it to work.

**Comment by ricardofbarros** [comment]
Yeah that is related to pkgCong release I'm waiting

**Comment by jefkoslowski** [comment]
Hey @ricardofbarros, I've just had the same issue here. Adding `"checkStyleDevDependencies": true` to `package.json` and checking the option "Check Style Dev Dependencies" did the trick, but I agree with @killswitch, this option isn't very clear on what it does.

Maybe changing it to something else?
