### ISSUE TITLE
Please include a current, updated changelog file.

### ISSUE THREAD

**Issue by faddah** [ricardofbarros/linter-js-standard#29]
if you would, please, include a changelog file that is updated & maintained for this repository so we can see what has been fixed in updates, even through Atom editor/updates.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by ricardofbarros** [comment]
Sure will do on the next release

**Comment by faddah** [comment]
thanx!

**Comment by peteruithoven** [comment]
Some tips and format suggestions:
http://keepachangelog.com/

**Comment by ricardofbarros** [comment]
Thank you @peteruithoven. Great stuff!

**Comment by ricardofbarros** [comment]
Fixed on commit 07ab992

Thanks @faddah and @peteruithoven

**Comment by faddah** [comment]
thanx for the changeling in version 2.2.0!
