### ISSUE TITLE
does not lint

### ISSUE THREAD

**Issue by despairblue** [ricardofbarros/linter-js-standard#3]
## Answering the questions from #1 

1. no error in the console while linting (tried saving the file and also starting it from the command palette, all other linters work)
2. `which node`: `/usr/local/bin/node`
3. `process.env.PATH`: `/home/despairblue/.rvm/bin:/home/despairblue/bin:/home/despairblue/.cabal/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-ndk64:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/despairblue/.linuxbrew/bin:/home/despairblue/node_modules/.bin:/opt/java6/bin:/home/despairblue/.gem/ruby/2.1.0/bin:/home/despairblue/go/bin`

Also I have *linter-js-standard* installed for a while now, couple of weeks at least, it actually never worked, not even with linter 0.11.0. I just haven't had the time to report it before now.

## Command History

```
     -0:08.6 selection:changed (atom-text-editor.editor.block-cursor-i-beam.is-focused)
     -0:06.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.block-cursor-i-beam.is-focused)
     -0:03.4 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini)
     -0:03.1 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:03.1 core:cancel (atom-text-editor.editor.mini)
     -0:02.7 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.block-cursor-i-beam.is-focused)
     -0:02.1 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:02.1 core:cancel (atom-text-editor.editor.mini)
     -0:01.7 command-palette:toggle (atom-text-editor.editor.block-cursor-i-beam.is-focused)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 bug-report:open (atom-text-editor.editor.block-cursor-i-beam.is-focused)
```

## Versions

* **Atom:**       0.190.0
* **Atom-Shell:** 0.22.3
* **OS:**         linux 3.14.26-1-lts
* **Misc**
    * apm  0.157.0
    * npm  2.5.1
    * node 0.10.35
    * python 2.7.9
    * git 2.3.5

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.6.3.</small>

**Comment by ricardofbarros** [comment]
Will look into this as soon as I got time, so it should be between today and tomorrow.

**Comment by despairblue** [comment]
:sparkles: thx :smiley:

**Comment by ricardofbarros** [comment]
Can you tell me which other linters you have enabled? Do you have js hint ?

**Comment by despairblue** [comment]
Yes, I can try to disable it tomorrow.

**Comment by despairblue** [comment]
I disabled *linter-jshint* and it still does nothing.

My other linters are:
**enabled:**
* linter-coffeelint
* linter-htmlhint
* linter-js-yaml
* linter-puppet-lint
* linter-shellcheck

**disabled:**
* linter-jshint
* linter-eslint

**Comment by ricardofbarros** [comment]
Hmm this is very strange, I'll try to duplicate this issue on ubuntu

**Comment by fannarsh** [comment]
I'm experiencing the same thing,
I'm using the default _Js Standard Executable Path_ but I have also the Js Standard npm package install globally

### Packages Installed
 - Sublime-Style-Column-Selection@1.2.3
 - base16-syntax@1.0.1
 - linter@0.12.0
 - linter-js-standard@0.1.4
 - linter-jshint@0.1.2 _disabled_

### Versions

* **Atom:**       0.191.0
* **Atom-Shell:** 0.22.3
* **OS:**         Mac OS X 10.10.2
* **Misc**
    * apm  0.157.0
    * npm  2.5.1
    * node 0.10.35
    * python 2.7.6
    * git 2.3.2

**Comment by fannarsh** [comment]
I have now updated to Atom: 0.192.0 no change

**Comment by fannarsh** [comment]
I downgraded linter-js-standard to 0.1.1 but that didn't change anything.

**Comment by ricardofbarros** [comment]
Finally I had time and tried to duplicate this issue and I duplicated successfully and I fixed it hopefully.

What was happening is that linter-js-standard linter was configured to received the error stream from stderr, and well it all ways worked for me like this. But I guess, with the most recent version of standard, feross changed from stderr to stdout, so I just configured linter-js-standard to catch the error stream from stdout.

I think the reason you guys couldn't see anything is because the most recent linter-js-standard installs standard@3.*.* and from that major release the std must have been switched.

Give it a try the last release and give me some feedback, thank you :smile:

**Comment by fannarsh** [comment]
:+1:  0.1.5 works for me

**Comment by ricardofbarros** [comment]
Great :smiley:, now let's wait for @despairblue feedback

**Comment by despairblue** [comment]
@ricardofbarros it works :clap: thanks :smiley:

**Comment by zeke** [comment]
Works for me now too. Thanks for fixing!
