### ISSUE TITLE
stdout not captured on Windows 8

### ISSUE THREAD

**Issue by timdp** [ricardofbarros/linter-js-standard#33]
I originally reported this as atom-community/linter#768:

> I was originally facing ricardofbarros/linter-js-standard#30, but I've further debugged the issue and it now looks like there is something awry in atom-linter 2.0.1. More specifically, on Windows 8 at least, Atom 1.0.2 seems unable to capture the child process's stdout.
> 
> I instrumented `helpers.coffee` to log the various stages of process creation. Basically, I see linter-js-standard invoke `atom.exe` with `ATOM_SHELL_INTERNAL_RUN_AS_NODE=1`. If the file has errors, then the status code differs, so it _is_ linting. However, there is never any standard output and hence no errors.
> 
> In a Windows Command Prompt, I did a `set` on the variable above and then ran `atom.exe` with the same arguments. Interestingly, it immediately went to a blank prompt and _then_ showed the output of the linter. It doesn't exhibit this behavior with a regular `node.exe`.
> 
> Additionally, I tried overriding `command` with `node.exe` (which is in my `PATH`), and that actually fixed the issue. Hence, it seems as though Electron run as Node behaves differently than a regular Node. It might very well be that the issue is with Electron instead. In that case, atom/electron#1463 should probably be reopened. However, since I've only seen it occur with atom-linter, I wanted to report it here first.

However, it now looks like this issue is linter-js-standard-specific. I've verified that linter-jshint works as expected, as @steelbrain suggested.

**Comment by ricardofbarros** [comment]
Thank you for reporting this, I will try to replicate on a windows machine.

**Comment by timdp** [comment]
It might be as simple as updating atom-linter. I see some Windows-related stuff in the log and 3.0.0 also literally just came out.

**Comment by ricardofbarros** [comment]
If I update atom-linter I might break this package for the rest of us, it all depends if there is now an option to disable the promise rejection.

**Comment by ricardofbarros** [comment]
Need to check the new updates on atom-linter

**Comment by timdp** [comment]
Yes. I just updated to 3.0.0 and it works if you pass in `{ throwOnStdErr: false }` to bypass `standard`'s silly welcome message.

**Comment by ricardofbarros** [comment]
Well it seems like it was  implemented that option `options.throwOnStdErr `

**Comment by ricardofbarros** [comment]
Yeah, exactly :smile:

**Comment by timdp** [comment]
Incidentally, #34 is still compatible as well. :-)

**Comment by ricardofbarros** [comment]
And the @3.0.0 works for you ?

**Comment by timdp** [comment]
Well, it's showing the linter messages I expected, so at least it's capturing stdout now.

**Comment by ricardofbarros** [comment]
Good, will review your PR and :arrow_up: atom-linter to 3.0.0

**Comment by timdp** [comment]
Cool. Thanks!

**Comment by ricardofbarros** [comment]
released 2.2.0, could you test if it solves this issue?

**Comment by timdp** [comment]
It sure does. :+1:
