### ISSUE TITLE
Add option to only activate on editor save?

### ISSUE THREAD

**Issue by jprichardson** [ricardofbarros/linter-js-standard#36]
I love that this is available - furthermore, it works wonderfully when opening up a JS file and instantly seeing all of the `standard` messages :)

However, it's a bit distracting when writing/editing code and then standard messages start showing up on the current line that I'm editing. 

Would you add an option so that it only activates when a `TextEditor` (`onDidSave`) is saved? Or maybe there's a better way to solve this? Do you run into this issue? Thanks.

**Comment by ricardofbarros** [comment]
Hey @jprichardson, what you are looking for is the [linter](https://github.com/atom-community/linter) package settings, there you can change your settings to lint on save, lint on edit, etc...

The linter-js-standard is only a plugin for AtomLinter and as such it will just provide an output of the linter errors/warning messages, everything else is AtomLinter responsibility, for instance the message display.

**Comment by jprichardson** [comment]
> Hey @jprichardson, what you are looking for is the linter package settings, there you can change your settings to lint on save, lint on edit, etc...

:+1: Awesome, thanks for this package!
