### ISSUE TITLE
Suggestion: get parser from project instead of builtin version

### ISSUE THREAD

**Issue by impinball** [ricardofbarros/linter-js-standard#38]
This would abstract away the need to keep the parser in this module itself, instead relying on the project to get the right module. `linter-eslint` does this.

**Comment by ricardofbarros** [comment]
Hey @impinball, thank you for your suggestion.

But I don't see how this would improve the current code base, it would introduce more complexity than simplicity. 

- I would have to keep an eye on .eslintrc files on projects to see if there is new plugins;
- I would have to pass some particular options to the eslint cliEngine (globals, etc..)
- .. and there should be more stuff to take into account.

I prefer update the versions on package.json over all those things I pointed out. Less headaches and less maintenance. :smile:

But give me your opinion, I could be wrong on this matter.

**Comment by impinball** [comment]
Okay... I may be wrong on the complexity side, but it allows for fewer
dependencies and easier configuration for users. And ESLint has its own
parsing algorithm to do all the magic. The main complexity is running
ESLint/standard from the root of the project instead of the root of this
prophecy. Also, any time someone wants a new parser, they can add it
themselves.

**Comment by ricardofbarros** [comment]
@impinball I will explore this option, but not with `eslint.CLIEngine` but with [standard-engine](https://github.com/Flet/standard-engine) this would reduce the complexity I mentioned above and  maybe we would see some performance improves.

**Comment by impinball** [comment]
Awesome!

**Comment by ricardofbarros** [comment]
This issue is dependent of this [issue](https://github.com/atom/loophole/issues/6)

**Comment by ricardofbarros** [comment]
Good news! An incoming major version is coming that will take this approach.
