### ISSUE TITLE
Show eslint rule that line is breaking in output

### ISSUE THREAD

**Issue by qrohlf** [ricardofbarros/linter-js-standard#39]
It would be great if linter-js-standard could show the rule name that a line is violating. This helps if you need to manually disable a specific rule for a line.

Sublime's linter-standard does this like so for a line that is breaking the 'react/prop-types' rule:

![screen shot 2015-08-05 at 9 20 05 am](https://cloud.githubusercontent.com/assets/347189/9091131/5bd44056-3b53-11e5-8e29-a03b937ba67f.png)

**Comment by ricardofbarros** [comment]
Yeah sure it does make sense and it's very doable. But only if the user can enable/disable showing the rule name

**Comment by qrohlf** [comment]
the sublime linter accomplishes this by passing the `--verbose` option to the `standard` bin. Perhaps a config option that allows the user to supply custom arguments to the selected linter would make sense?

**Comment by ricardofbarros** [comment]
Yeah I know I pass it as well but I choose to left it out from the actual message

**Comment by ricardofbarros** [comment]
Feature added on the last release (2.4.0)

Thank you for your input @qrohlf
