### ISSUE TITLE
Failed to load the linter-js-standard package

### ISSUE THREAD

**Issue by killsos** [ricardofbarros/linter-js-standard#44]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) package, v2.5.0

### Stack Trace

Failed to load the linter-js-standard package

```
At Cannot find module 'concat-map'

Error: Cannot find module 'concat-map'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/killsos/.atom/packages/linter-js-standard/node_modules/minimatch/node_modules/brace-expansion/index.js:1:79)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui-slim",
      "monokai"
    ],
    "disabledPackages": [
      "Atom-Syntax-highlighting-for-Sass",
      "Atom-Syntax-highlighting-for-Sass",
      "Atom-Syntax-highlighting-for-Sass",
      "Atom-Syntax-highlighting-for-Sass",
      "Atom-Syntax-highlighting-for-Sass",
      "Atom-Syntax-highlighting-for-Sass",
      "Atom-Syntax-highlighting-for-Sass",
      "Atom-Syntax-highlighting-for-Sass",
      "Atom-Syntax-highlighting-for-Sass",
      "Atom-Syntax-highlighting-for-Sass",
      "Atom-Syntax-highlighting-for-Sass",
      "Atom-Syntax-highlighting-for-Sass"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-dark-ui-slim, v0.47.1
atom-jshint, v2.0.0
autocomplete-paths, v1.0.2
autocomplete-sass, v0.1.0
color-picker, v2.0.11
docblockr, v0.7.3
emmet, v2.3.12
express-complete, v0.2.0
file-icons, v1.6.7
html-id-class-snippets, v1.4.1
javascript-snippets, v1.0.0
linter, v1.4.3
linter-js-standard, v2.5.0
minimap, v4.13.1
monokai, v0.18.0
pigments, v0.11.0
pretty-json, v0.4.1
sass-watch, v0.3.1
travis-ci-status, v0.16.0
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by ricardofbarros** [comment]
hmm strange, please uninstall and install again. It seems like it was a problem with a dependency dependency of this package.

**Comment by killsos** [comment]
tks

2015-08-22 22:56 GMT+08:00 Ricardo Barros <notifications@github.com>:

**Comment by ricardofbarros** [comment]
Did it work?

**Comment by blakeembrey** [comment]
@ricardofbarros The same issue now exists because you haven't added `loophole` as a dependency.

**Comment by ricardofbarros** [comment]
oww my god, terrible sorry for this

**Comment by ricardofbarros** [comment]
Could you try it now? `Q` was missing as well.

**Comment by blakeembrey** [comment]
No more error on `loophope` :+1:

**Comment by emaza** [comment]
Hi, This error is displayed always I open atom with proyec folder.

> Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

I use
`#!/usr/bin/env node`
`'use strict'`

 in all my proyect files. Maybe some file in the folder node_modules do not use 'use strict' tag but I have .gitignore file whith node_modules exclude.

I have atom 1.6.2 in ubuntu 14.04 whith linter-js-standard 3.6.0

thanks
 

> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:77:42)
>     at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
>     at Object.<anonymous> (/home/edu/.atom/packages/linter-js-standard/lib/init.js:4:21)
>     at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
>     at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
>     at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:720:27)
>     at /usr/share/atom/resources/app.asar/src/package.js:116:28
>     at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
>     at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
>     at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:445:14)
>     at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:395:14)
>     at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:684:21)
>     at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
>     at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
>     at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)

**Comment by Arcanemagus** [comment]
@emaza Your Atom version is very old, update to the current version and you should be fine.

**Comment by emaza** [comment]
oh!!, sorry.
I did it and all it's ok now
Thanks

**Comment by yar0d** [comment]
Having the same error:

1. Just enable linter-js-standard module

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: "Arch Linux"
**Thrown From**: [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) package 3.9.0


### Stack Trace

Failed to load the linter-js-standard package

```
At Cannot find module './utils/select-style'

Error: Cannot find module './utils/select-style'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-js-standard/lib/init.js:3:19)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:792:28
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-save-all 0.4.1 
autoclose-html 0.23.0 
busy-signal 1.3.0 
color-picker 2.2.5 
docblockr 0.9.3 
emmet 2.4.3 
git-plus 7.3.3 
git-time-machine 1.5.7 
highlight-selected 0.13.1 
intentions 1.1.2 
intentions-colorpicker 1.0.1 
language-docker 1.1.7 
language-ejs 0.4.0 
language-groovy 0.6.0 
language-vue 0.21.2 
linter 2.1.2 
linter-eslint 8.1.4 
linter-js-standard 3.9.0 
linter-jshint 3.0.3 
linter-jsonlint 1.3.0 
linter-less 2.6.0 
linter-ui-default 1.2.1 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
minimap-pigments 0.2.2 
monokai 0.22.0 
pigments 0.39.1 
seti-ui 1.7.0 
standard-formatter 2.8.0 
standardjs-snippets 2.6.0 
Sublime-Style-Column-Selection 1.7.4 
terminal-plus 0.14.5 
todo-show 1.11.0 
```
