### ISSUE TITLE
Disable "trailing spaces" warning?

### ISSUE THREAD

**Issue by levity** [ricardofbarros/linter-js-standard#45]
I would like to disable the warning -- not because I disagree with the standard, but because it's very distracting, as it constantly pops up when I'm typing and pause to think. Not to mention I already have the editor set up to remove trailing spaces, since Atom includes the Whitespace package by default.

**Comment by ricardofbarros** [comment]
I can't do that but you could configure the linter to only lint when you save so it doesn't distract you. To do that you need to go Linter (not linter-js-standard) settings and untick the box that says `Lint on fly`

**Comment by levity** [comment]
That's a good solution for me, thanks!
