### ISSUE TITLE
Something went wrong internally.

### ISSUE THREAD

**Issue by saschagehlich** [ricardofbarros/linter-js-standard#46]
https://github.com/ricardofbarros/linter-js-standard/blob/master/lib/linter-js-standard.js#L29

This seems to be triggered when you're in a JS file and save the file under a different name (Using `Save as...`)

**Comment by ricardofbarros** [comment]
Related with #37. This annoying warning is currently fixed on the branch feature/eval-cli, I'm just finishing the new lint markdown fenced code feature and I will release a major version that won't have that issue.
