### ISSUE TITLE
Install `linter` automatically.

### ISSUE THREAD

**Issue by k2b6s9j** [ricardofbarros/linter-js-standard#51]
By using [`atom-package-deps`](https://github.com/steelbrain/package-deps) you are able to install `linter` automatically on activation. This will allow new Atom users to install only your package and nothing else, removing one step from the installation process.

Please see AtomLinter/linter-ruby#38 for example.

**Comment by ricardofbarros** [comment]
Cool. I will check this out that package seems awesome

**Comment by ricardofbarros** [comment]
That would be a very cool to implement but I will stall this "feature" until this [issue](https://github.com/steelbrain/package-deps/issues/8) get solved.

**Comment by ricardofbarros** [comment]
Implemented on the last release. (3.2.0)
