### ISSUE TITLE
Use badges instead of text for eslint rules

### ISSUE THREAD

**Issue by ricardofbarros** [ricardofbarros/linter-js-standard#54]
[Example](https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L124)

**Comment by sonicdoe** [comment]
Since Atom Linter v2 now [has support for pluggable UI providers](http://steelbrain.me/2017/03/13/linter-v2-released.html) and [linter-eslint removed this custom badge styling](https://github.com/AtomLinter/linter-eslint/pull/814), I don’t think this enhancement would be worth it nowadays.
