### ISSUE TITLE
Deprecate config

### ISSUE THREAD

**Issue by ricardofbarros** [ricardofbarros/linter-js-standard#55]
[Example](https://github.com/gandm/language-babel/blob/master/lib/transpiler.coffee#L90)

**Comment by sonicdoe** [comment]
Permalink to the example: [lib/transpiler.coffee#L263-L285](https://github.com/gandm/language-babel/blob/d7d260522eb0f6528ea8558beb1bda54c5d25eba/lib/transpiler.coffee#L263-L285). This has now been used for the first time in https://github.com/ricardofbarros/linter-js-standard/commit/e87d36beb46ce274bc97b68e79be87a0acdb9826.
