### ISSUE TITLE
Disable when .jshintrc file is available

### ISSUE THREAD

**Issue by gillesdemey** [ricardofbarros/linter-js-standard#56]
I'd be awesome to have an option that disables the Standard linter when a .jshintrc file is in the project.

I'm using Standard for most of my personal projects and JSHint for some others (mostly work related or older projects) — and switching between linters is currently a pain.

**Comment by ricardofbarros** [comment]
Hello, yeah it does make sense.
But why don't you configure `honorStyleSettings` to true so that your plugin will only lint your files if it finds `standard`, `semistandard`, `hapiness` in your package.json `devDependencies`.

**Comment by gillesdemey** [comment]
Isn't it called `checkStyleDevDependencies`? That's what I'm deducing from the README :)

**Comment by ricardofbarros** [comment]
Yes, you're correct. Sorry I must have confused the settings.

**Comment by ricardofbarros** [comment]
Does this workflow work for you or do you need this feature implemented?

**Comment by gillesdemey** [comment]
Yea this works, thanks!
