### ISSUE TITLE
ignored globals in package.json

### ISSUE THREAD

**Issue by nikmartin** [ricardofbarros/linter-js-standard#58]
I added this to the package.json file in the root of my node.js app:
```
  "semistandard": {
    "global": [ "__base" ]
  }
```
and in hundreds of files in the project, I have this:
```
var util = require(__base + '/models/schemas/util');
```

But still continually get this message:
![screenshot from 2015-10-09 09-03-47](https://cloud.githubusercontent.com/assets/1226452/10395858/d1c5b8a0-6e64-11e5-8ca8-2d3a4249cd80.png)

**Comment by sandnuggah** [comment]
```js
{
  "semistandard": {
    "globals": [ "__base" ] // the key is `globals`, not `global`
  }
}
```

Restart Atom for changes to have effect.

**Comment by nikmartin** [comment]
OK, I couldn't find any docs, so I went to the source, and found this:
`  styleSettings.global = styleSettings.global || styleSettings.globals` So I just took the first option `global` and used it.

**Comment by nikmartin** [comment]
Also, That didn't have any effect:
```
"semistandard": {
    "globals": [
      "__base"
    ]
  }
```
![screenshot from 2015-10-13 08-01-19](https://cloud.githubusercontent.com/assets/1226452/10455420/cc346f5c-7180-11e5-823b-6d28615de9e3.png)

**Comment by sandnuggah** [comment]
Have a look here

https://github.com/feross/standard/blob/master/README.md#i-use-a-library-that-pollutes-the-global-namespace-how-do-i-prevent-variable-is-not-defined-errors

**Comment by nikmartin** [comment]
I don't know what it's not honoring the setting then, I have tried it both as:

```
"semistandard": {
    "globals": [
      "__base"
    ]
  }
```
and
```
"semistandard": {
    "global": [
      "__base"
    ]
  }
```

Restarting each time, and the warnings never go away.

**Comment by ricardofbarros** [comment]
Hey guys, thanks for your help @sandnuggah.

Hmm that's awkward, let me take a look.

**Comment by nikmartin** [comment]
If you need me to debug anything, let me know.

**Comment by ricardofbarros** [comment]
Can you do something for me? `cd /to/the/directory/where/is/your/file` and run `semistandard yourFilename.js` and tell me if it shows the same warning on the terminal.

**Comment by nikmartin** [comment]
In a file with only a single 'not defined' warning I get no warnings running semistandard on the command line. In a file with a 'not defined' + other warnings, I only get the other warnings.

**Comment by ricardofbarros** [comment]
What settings you have ticked on `linter-js-standard` plugin settings?

**Comment by nikmartin** [comment]
None are selected at the moment: 
"linter-js-standard":
    style: "semi-standard"

**Comment by ricardofbarros** [comment]
Well if you want your style settings to be honoured you need to tick the `Honor Style Settings`

**Comment by ricardofbarros** [comment]
So did it worked?

**Comment by nikmartin** [comment]
I checked Honor Style Settings and it is working now.  I took the README literally, and since it says:
```
Current style settings supported:
- `ignore`
- `parser`
```
I didn't think it applied to globals. Should I add some documentation about it and submit a pull request?  I didn't even know how to add support for globals until I read the source code and the standard lib's readme.

**Comment by ricardofbarros** [comment]
Sure @nikmartin I would appreciate that :)

**Comment by ricardofbarros** [comment]
#66 Merged, thanks for the PR @nikmartin
