### ISSUE TITLE
Viewing ignored file prevents further linting

### ISSUE THREAD

**Issue by shaungrady** [ricardofbarros/linter-js-standard#64]
I'm not sure what the steps to troubleshoot this are—I'm not even sure it's an issue with this package specifically—but here's what I'm seeing...

**package.json**

``` json
{
  "standard": {
    "ignore": [
      "app/assets/javascripts/vendor/*.js"
    ]
  }
}
```

Linting works as expected until I open an ignored file within `app/assets/javascripts/vendor`, at which point linting ceases to function on every file. Invoking the linter on a file manually has no effect. The only way I'm able to get linting to function properly again is to restart Atom.

OS X 10.11.1
Atom 1.0.19

**Comment by ricardofbarros** [comment]
Hmm interesting... I will take a look. :+1:

**Comment by shaungrady** [comment]
Let me know if you'd like to me provide any additional information

**Comment by daniel-ro** [comment]
I also encounter this problem, and I try to debug it but I'm not familiar with Atom enough to understand exactly what going on there but I found something that maybe will help you:

1. In [select-style.js](https://github.com/ricardofbarros/linter-js-standard/blob/master/lib/utils/select-style.js) inside "requireWithLocalOverride" function, the require loader always throw an error and goes to the catch part.
2. in the same file, inside "pickStandard" function, the returning object (Linter object) after opening ignored file is always with cmd == 'no-style'.

@ricardofbarros, would be great if can look at this and help me solve the issue.
Thanks!

**Comment by sonicdoe** [comment]
From what I can tell, this has been fixed with https://github.com/ricardofbarros/linter-js-standard/commit/b863435dbaa7c805d9d33fb2cb595f9f8b3c44c0 (v3.8.0 or later).
