### ISSUE TITLE
The init script in readme will prevent Atom's Packages/Themes/Updates panels from working

### ISSUE THREAD

**Issue by gsklee** [ricardofbarros/linter-js-standard#8]
Putting this in my init script as suggested by the readme will stop the packages panel etc. from working:

```coffeescript
sys = require('sys')
exec = require('child_process').exec;

exec "source ~/.bash_profile && echo $PATH", (err, stdout) ->
  process.env.PATH = stdout.replace '\n', ''
```

**Comment by ricardofbarros** [comment]
My Atom is working fine with that init script, could you open the console and print here what the console is outputting?

**Comment by ricardofbarros** [comment]
Is this still happening?

**Comment by gsklee** [comment]
I removed the script and the panels are once again working - and the linting is working as well.
