### ISSUE TITLE
Contructor Space

### ISSUE THREAD

**Issue by coreybutler** [ricardofbarros/linter-js-standard#80]
I'm not entirely sure where this issue is stemming from, but the plugin detects an error in ES6/ES2015 style syntax with a constructor method... specifically identifying that a space is required between the `constructor` attribute and the `()`:

See line 27:

![image](https://cloud.githubusercontent.com/assets/770982/12489932/848996ee-c038-11e5-89e7-d9ccfab810ee.png)

Adding the space to the constructor removes the error, as expected:

![image](https://cloud.githubusercontent.com/assets/770982/12489949/9bd5b526-c038-11e5-8df3-4f6fd9db617c.png)

However; saving this removes the space, reverting right back to the original problem:

![image](https://cloud.githubusercontent.com/assets/770982/12489932/848996ee-c038-11e5-89e7-d9ccfab810ee.png)

As a result, I have to exit Atom and add the space with another editor. This seemingly small problem is way more annoying than I anticipated... especially since my unit testing enforces proper js standard syntax. I've had scenarios where I'll modify something completely unrelated to the constructor method, but saving the file in Atom will "auto-correct" by stripping the space out.

**Comment by ricardofbarros** [comment]
I was unable to reproduce.
