### ISSUE TITLE
Where does the "no-spaces inside parens" rule come from?

### ISSUE THREAD

**Issue by corysimmons** [ricardofbarros/linter-js-standard#81]
`if ( x > y )` pops up in linter because of the spaces in the parens. I wasn't able to track down this specification anywhere.

It's fine, just curious where this warning comes from. :8ball:

**Comment by tonyghita** [comment]
@corysimmons I believe it comes from the `eslint-config-standard` package. 
See https://github.com/feross/eslint-config-standard/blob/master/eslintrc.json#L126

**Comment by corysimmons** [comment]
Ah you're right. Overlooked it. Thanks :100:

**Comment by tonyghita** [comment]
Cheers! :beers:

**Comment by corysimmons** [comment]
![image](https://cloud.githubusercontent.com/assets/224636/13129845/a7731a10-d5ad-11e5-96d4-8140f1102707.png)

**Comment by tonyghita** [comment]
:joy:
