### ISSUE TITLE
What's the intention of checkStyleDevDependencies

### ISSUE THREAD

**Issue by lygstate** [ricardofbarros/linter-js-standard#82]

**Comment by tonyghita** [comment]
@lygstate it only runs `linter-js-standard` if the package.json of the project contains one of the linters as a dependency.

See https://github.com/ricardofbarros/linter-js-standard/blob/master/lib/init.js#L13-L18

**Comment by ricardofbarros** [comment]
Thank you @tonyghita for the explanation 😃
