### ISSUE TITLE
Binding callback functions with ES7 operator

### ISSUE THREAD

**Issue by carlesba** [ricardofbarros/linter-js-standard#84]
I'm trying to use the es7 operator on jsx, like:

``` jsx
<Component callback={::method} />
```

and the linter is throwing an error, but Babel doesn't break so I guess this shouldn't be an error. Although this is ES7 syntax, it's supported by react jsx

[link](http://blog.jeremyfairbank.com/javascript/javascript-es7-function-bind-syntax/)
[link2](http://stackoverflow.com/questions/31220078/javascript-double-colon-es7-proposal)

**Comment by pukapukan** [comment]
+1

**Comment by ricardofbarros** [comment]
Hey @carlesba and @pukapukan , this should be supported by using a custom parser. https://github.com/feross/standard#how-do-i-use-experimental-javascript-es-next-features

on your package.json

  "standard": {
    "parser": "babel-eslint"
  }
Don't forget to npm i babel-eslint --save-dev
