### ISSUE TITLE
Should not lint html files

### ISSUE THREAD

**Issue by nopnop** [ricardofbarros/linter-js-standard#9]
Maybe the linter's scope is to greedy in the syntax list for linter: [linter-js-standard.coffee#10](https://github.com/ricardofbarros/linter-js-standard/blob/master/lib/linter-js-standard.coffee#L10)

By using `text.html.basic`, any html file is *linted*, thus a lot of js-standard errors are reported:

- `'React' must be in scope when using JSX`
- `Unexpected token !` for `<!DOCTYPE html>`
- etc.

**Comment by ricardofbarros** [comment]
Maybe you're right, standard wasn't made to lint html files where you can have css and js. I copied the linter scope of jshint linter. Fix incoming.

**Comment by ricardofbarros** [comment]
Done. removed `text.html.basic` on the latest release v0.2.4, but I keep `source.js.jquery` maybe I should remove it as well, but for now I will keep it.
