### ISSUE TITLE
Mocha Syntax unknown

### ISSUE THREAD

**Issue by lkshrk** [ricardofbarros/linter-js-standard#95]
I'm not sure if this is an issue or an enhancement request:
When using the current version of the linter some of the Mocha Syntax is unknown, i.e.

`it`
`describe`
`...`

Thanks a lot,
Lukas

**Comment by ricardofbarros** [comment]
Hey @lkshrk , please take a look at [this](https://github.com/ricardofbarros/linter-js-standard#global-variable-support). I think that will solve your problem.
