### ISSUE TITLE
Is it possible to use a custom / more recent version of the linter?

### ISSUE THREAD

**Issue by sbromberger** [ricardofbarros/linter-js-standard#96]
https://github.com/Flet/semistandard/pull/37 is available in 7.0.3 which is apparently newer than what the plugin uses by default right now. Is there a way to configure linter-js-standard to use a specific version of the linter?

**Comment by sbromberger** [comment]
See also #93.

**Comment by anthonyringoet** [comment]
Something like greenkeeper could be a nice help to keep these dependencies up to date https://greenkeeper.io/

**Comment by joshuajabbour** [comment]
It would be awesome if this plugin could just use the version of standard that's in the package.json of the files you're linting, at least when the `Check for standard` option is set (I'm not sure if that's possible with Atom).
