### ISSUE TITLE
Make "Honor Style Settings" checked by default

### ISSUE THREAD

**Issue by LinusU** [ricardofbarros/linter-js-standard#98]
I think that it would be very useful if "Honor Style Settings" could be checked by default, is there any specific reason it isn't?

**Comment by ricardofbarros** [comment]
hey @LinusU, as of `3.3.0` the option "Honor Style Settings" default is true. Thanks for the heads up.

**Comment by LinusU** [comment]
Awesome :raised_hands: thanks
